#!/usr/bin/env bash

if [ ! -z "${DEV_BASE// }" ]
then
  cd $DEV_BASE/py/xlreg_py
  
  rm -rf build/* tmp/* 
  
  pySloc -L py xlRegClient.py -X cover  -X dist -v $@
else
  echo "DEV_BASE is not defined"
fi
