[meta]
version = "0.1.0"

[project]
name = "xlreg_py"
package = "xlreg_py"
main_lang = "py"
version = "0.1.30"
version_date = "2018-02-16"
author = "Jim Dixon"
author_email = "jddixon@gmail.com"
copyright = "2014-2017"
description = "Python 3 client for xlReg server"
dev_status = "2"
license = "mit"
relpath = "py/xlreg_py"
state = "private"
url = "https://jddixon.github.io/xlreg_py"

[py]
packages = [ "xlreg",]
package_dir = [ "src",]
test_dir = [ "tests",]
py_modules = [ "xlreg_client",]
scripts = [ "src/xlreg_client.py",]
ext_modules = []
distshare = []
requirements = []
test_requirements = []
