# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


DESCRIPTOR = descriptor.FileDescriptor(
    name='p.proto',
    package='reg',
    serialized_pb='\n\x07p.proto\x12\x03reg\"\xce\x05\n\x08XLRegMsg\x12\x1d\n\x02Op\x18\x01 \x01(\x0e\x32\x11.reg.XLRegMsg.Tag\x12\r\n\x05\x41\x65sIV\x18\x02 \x01(\x0c\x12\x0e\n\x06\x41\x65sKey\x18\x03 \x01(\x0c\x12\r\n\x05Salt1\x18\x04 \x01(\x0c\x12\r\n\x05Salt2\x18\x05 \x01(\x0c\x12\x0f\n\x07Version\x18\x06 \x01(\r\x12\x12\n\nClientName\x18\x08 \x01(\t\x12\x10\n\x08\x43lientID\x18\t \x01(\x0c\x12\x13\n\x0b\x43lientAttrs\x18\n \x01(\x04\x12(\n\x0b\x43lientSpecs\x18\x0b \x01(\x0b\x32\x13.reg.XLRegMsg.Token\x12\x11\n\tClusterID\x18\r \x01(\x0c\x12\x13\n\x0b\x43lusterName\x18\x0e \x01(\t\x12\x13\n\x0b\x43lusterSize\x18\x0f \x01(\r\x12\x14\n\x0c\x43lusterAttrs\x18\x10 \x01(\x04\x12\x15\n\rEndPointCount\x18\x11 \x01(\r\x12\r\n\x05Which\x18\x14 \x01(\x04\x12#\n\x06Tokens\x18\x15 \x03(\x0b\x32\x13.reg.XLRegMsg.Token\x12\x0e\n\x06\x44igSig\x18\x16 \x01(\x0c\x12\x0f\n\x07\x45rrDesc\x18\x17 \x01(\t\x1ar\n\x05Token\x12\x0c\n\x04Name\x18\x01 \x01(\t\x12\r\n\x05\x41ttrs\x18\x02 \x01(\x04\x12\n\n\x02ID\x18\x03 \x01(\x0c\x12\x10\n\x08\x43ommsKey\x18\x04 \x01(\x0c\x12\x0e\n\x06SigKey\x18\x05 \x01(\x0c\x12\x0e\n\x06MyEnds\x18\x06 \x03(\t\x12\x0e\n\x06\x44igSig\x18\x07 \x01(\x0c\"\xbc\x01\n\x03Tag\x12\x12\n\x0eRegCredRequest\x10\x01\x12\x10\n\x0cRegCredReply\x10\x02\x12\n\n\x06\x43lient\x10\x03\x12\x0c\n\x08\x43lientOK\x10\x04\x12\n\n\x06\x43reate\x10\x05\x12\x0f\n\x0b\x43reateReply\x10\x06\x12\x08\n\x04Join\x10\x07\x12\r\n\tJoinReply\x10\x08\x12\x0e\n\nGetCluster\x10\t\x12\x12\n\x0e\x43lusterMembers\x10\n\x12\x07\n\x03\x42ye\x10\x0b\x12\x07\n\x03\x41\x63k\x10\x0c\x12\t\n\x05\x45rror\x10\r')


_XLREGMSG_TAG = descriptor.EnumDescriptor(
    name='Tag',
    full_name='reg.XLRegMsg.Tag',
    filename=None,
    file=DESCRIPTOR,
    values=[
        descriptor.EnumValueDescriptor(
            name='RegCredRequest', index=0, number=1,
            options=None,
            type=None),
        descriptor.EnumValueDescriptor(
            name='RegCredReply', index=1, number=2,
            options=None,
            type=None),
        descriptor.EnumValueDescriptor(
            name='Client', index=2, number=3,
            options=None,
            type=None),
        descriptor.EnumValueDescriptor(
            name='ClientOK', index=3, number=4,
            options=None,
            type=None),
        descriptor.EnumValueDescriptor(
            name='Create', index=4, number=5,
            options=None,
            type=None),
        descriptor.EnumValueDescriptor(
            name='CreateReply', index=5, number=6,
            options=None,
            type=None),
        descriptor.EnumValueDescriptor(
            name='Join', index=6, number=7,
            options=None,
            type=None),
        descriptor.EnumValueDescriptor(
            name='JoinReply', index=7, number=8,
            options=None,
            type=None),
        descriptor.EnumValueDescriptor(
            name='GetCluster', index=8, number=9,
            options=None,
            type=None),
        descriptor.EnumValueDescriptor(
            name='ClusterMembers', index=9, number=10,
            options=None,
            type=None),
        descriptor.EnumValueDescriptor(
            name='Bye', index=10, number=11,
            options=None,
            type=None),
        descriptor.EnumValueDescriptor(
            name='Ack', index=11, number=12,
            options=None,
            type=None),
        descriptor.EnumValueDescriptor(
            name='Error', index=12, number=13,
            options=None,
            type=None),
    ],
    containing_type=None,
    options=None,
    serialized_start=547,
    serialized_end=735,
)


_XLREGMSG_TOKEN = descriptor.Descriptor(
    name='Token',
    full_name='reg.XLRegMsg.Token',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        descriptor.FieldDescriptor(
            name='Name', full_name='reg.XLRegMsg.Token.Name', index=0,
            number=1, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=str("", "utf-8"),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
        descriptor.FieldDescriptor(
            name='Attrs', full_name='reg.XLRegMsg.Token.Attrs', index=1,
            number=2, type=4, cpp_type=4, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
        descriptor.FieldDescriptor(
            name='ID', full_name='reg.XLRegMsg.Token.ID', index=2,
            number=3, type=12, cpp_type=9, label=1,
            has_default_value=False, default_value="",
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
        descriptor.FieldDescriptor(
            name='CommsKey', full_name='reg.XLRegMsg.Token.CommsKey', index=3,
            number=4, type=12, cpp_type=9, label=1,
            has_default_value=False, default_value="",
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
        descriptor.FieldDescriptor(
            name='SigKey', full_name='reg.XLRegMsg.Token.SigKey', index=4,
            number=5, type=12, cpp_type=9, label=1,
            has_default_value=False, default_value="",
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
        descriptor.FieldDescriptor(
            name='MyEnds', full_name='reg.XLRegMsg.Token.MyEnds', index=5,
            number=6, type=9, cpp_type=9, label=3,
            has_default_value=False, default_value=[],
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
        descriptor.FieldDescriptor(
            name='DigSig', full_name='reg.XLRegMsg.Token.DigSig', index=6,
            number=7, type=12, cpp_type=9, label=1,
            has_default_value=False, default_value="",
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    options=None,
    is_extendable=False,
    extension_ranges=[],
    serialized_start=430,
    serialized_end=544,
)

_XLREGMSG = descriptor.Descriptor(
    name='XLRegMsg',
    full_name='reg.XLRegMsg',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        descriptor.FieldDescriptor(
            name='Op', full_name='reg.XLRegMsg.Op', index=0,
            number=1, type=14, cpp_type=8, label=1,
            has_default_value=False, default_value=1,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
        descriptor.FieldDescriptor(
            name='AesIV', full_name='reg.XLRegMsg.AesIV', index=1,
            number=2, type=12, cpp_type=9, label=1,
            has_default_value=False, default_value="",
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
        descriptor.FieldDescriptor(
            name='AesKey', full_name='reg.XLRegMsg.AesKey', index=2,
            number=3, type=12, cpp_type=9, label=1,
            has_default_value=False, default_value="",
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
        descriptor.FieldDescriptor(
            name='Salt1', full_name='reg.XLRegMsg.Salt1', index=3,
            number=4, type=12, cpp_type=9, label=1,
            has_default_value=False, default_value="",
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
        descriptor.FieldDescriptor(
            name='Salt2', full_name='reg.XLRegMsg.Salt2', index=4,
            number=5, type=12, cpp_type=9, label=1,
            has_default_value=False, default_value="",
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
        descriptor.FieldDescriptor(
            name='Version', full_name='reg.XLRegMsg.Version', index=5,
            number=6, type=13, cpp_type=3, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
        descriptor.FieldDescriptor(
            name='ClientName', full_name='reg.XLRegMsg.ClientName', index=6,
            number=8, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=str("", "utf-8"),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
        descriptor.FieldDescriptor(
            name='ClientID', full_name='reg.XLRegMsg.ClientID', index=7,
            number=9, type=12, cpp_type=9, label=1,
            has_default_value=False, default_value="",
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
        descriptor.FieldDescriptor(
            name='ClientAttrs', full_name='reg.XLRegMsg.ClientAttrs', index=8,
            number=10, type=4, cpp_type=4, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
        descriptor.FieldDescriptor(
            name='ClientSpecs', full_name='reg.XLRegMsg.ClientSpecs', index=9,
            number=11, type=11, cpp_type=10, label=1,
            has_default_value=False, default_value=None,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
        descriptor.FieldDescriptor(
            name='ClusterID', full_name='reg.XLRegMsg.ClusterID', index=10,
            number=13, type=12, cpp_type=9, label=1,
            has_default_value=False, default_value="",
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
        descriptor.FieldDescriptor(
            name='ClusterName', full_name='reg.XLRegMsg.ClusterName', index=11,
            number=14, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=str("", "utf-8"),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
        descriptor.FieldDescriptor(
            name='ClusterSize', full_name='reg.XLRegMsg.ClusterSize', index=12,
            number=15, type=13, cpp_type=3, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
        descriptor.FieldDescriptor(
            name='ClusterAttrs', full_name='reg.XLRegMsg.ClusterAttrs', index=13,
            number=16, type=4, cpp_type=4, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
        descriptor.FieldDescriptor(
            name='EndPointCount', full_name='reg.XLRegMsg.EndPointCount', index=14,
            number=17, type=13, cpp_type=3, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
        descriptor.FieldDescriptor(
            name='Which', full_name='reg.XLRegMsg.Which', index=15,
            number=20, type=4, cpp_type=4, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
        descriptor.FieldDescriptor(
            name='Tokens', full_name='reg.XLRegMsg.Tokens', index=16,
            number=21, type=11, cpp_type=10, label=3,
            has_default_value=False, default_value=[],
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
        descriptor.FieldDescriptor(
            name='DigSig', full_name='reg.XLRegMsg.DigSig', index=17,
            number=22, type=12, cpp_type=9, label=1,
            has_default_value=False, default_value="",
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
        descriptor.FieldDescriptor(
            name='ErrDesc', full_name='reg.XLRegMsg.ErrDesc', index=18,
            number=23, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=str("", "utf-8"),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
    ],
    extensions=[
    ],
    nested_types=[_XLREGMSG_TOKEN, ],
    enum_types=[
        _XLREGMSG_TAG,
    ],
    options=None,
    is_extendable=False,
    extension_ranges=[],
    serialized_start=17,
    serialized_end=735,
)

_XLREGMSG_TOKEN.containing_type = _XLREGMSG
_XLREGMSG.fields_by_name['Op'].enum_type = _XLREGMSG_TAG
_XLREGMSG.fields_by_name['ClientSpecs'].message_type = _XLREGMSG_TOKEN
_XLREGMSG.fields_by_name['Tokens'].message_type = _XLREGMSG_TOKEN
_XLREGMSG_TAG.containing_type = _XLREGMSG
DESCRIPTOR.message_types_by_name['XLRegMsg'] = _XLREGMSG


class XLRegMsg(message.Message,
               metaclass=reflection.GeneratedProtocolMessageType):

    class Token(message.Message,
                metaclass=reflection.GeneratedProtocolMessageType):
        DESCRIPTOR = _XLREGMSG_TOKEN

        # @@protoc_insertion_point(class_scope:reg.XLRegMsg.Token)
    DESCRIPTOR = _XLREGMSG

    # @@protoc_insertion_point(class_scope:reg.XLRegMsg)

# @@protoc_insertion_point(module_scope)
